### ISSUE TITLE
Observes AppScoped not working

### ISSUE THREAD

**Issue by johnament** [arquillian/arquillian-container-weld#24]
Take a look at https://github.com/hammock-project/microprofile-samples/blob/7d9a367f12922e4eaff49d5dbd967578d045f016/microprofile-sample-canonical/src/test/java/io/microprofile/sample/canonical/rest/TopCDsEndpointTest.java#L70 and https://github.com/hammock-project/hammock/blob/d3a134e372cd0c35001f73ff8132c7ee705837f0/web-spi/src/main/java/ws/ament/hammock/web/spi/StartWebServer.java

It seems that the start of an app scope event isn't working quite right, or maybe there's some hidden thing I'm missing.

To clarify, to get my webserver to start, I had to manually call the method.  It works fine when using an uber-jar though (against Weld 2.3.5)

**Comment by johnament** [comment]
A little more digging.

in WeldStartup, this block fires the event

```
if (modules != null) {
            // fire @Initialized(ApplicationScoped.class) for non-web modules
            // web modules are handled by HttpContextLifecycle
            for (BeanDeploymentModule module : modules) {
                if (!module.isWebModule()) {
                    module.fireEvent(Object.class, ContextEvent.APPLICATION_INITIALIZED, InitializedLiteral.APPLICATION);
                }
            }
        }
```

In the container, the modules are null.

**Comment by tremes** [comment]
Thanks for report @johnament. It really looks like a problem. I am looking into this.

**Comment by tremes** [comment]
Fixed https://github.com/arquillian/arquillian-container-weld/commit/3e38abf716200a0a44acdd06281bd3224d2bfed1

**Comment by johnament** [comment]
@tremes  i'm a bit worried about the change put it.  it seems like we're bypassing why it fails (modules == null).  Any idea why the modules are null?

**Comment by tremes** [comment]
Because there are not any modules in SE env.
