### ISSUE TITLE
arquillian-weld-embedded requires JTA

### ISSUE THREAD

**Issue by johnament** [arquillian/arquillian-container-weld#25]
Even if my app does not use JTA, arquillian-weld-embedded requires JTA on the classpath.  No impl required, but the jar must be there.

If it's a required dependency, it should be properly marked in the pom.

**Comment by tremes** [comment]
I am not sure what do you mean here. What do you mean by "properly marked in the pom" please? Isn't https://github.com/arquillian/arquillian-container-weld/blob/master/pom.xml#L145 sufficient?

**Comment by johnament** [comment]
No, its not.  Take a look at https://github.com/hammock-project/hammock/blob/master/util-metrics/pom.xml#L87

I had to add JTA dependency to the pom to make the tests run.  Without JTA, the tests don't even run (even though I'm not using JTA).

**Comment by tremes** [comment]
Does this https://github.com/arquillian/arquillian-container-weld/pull/26 solve your issue please?
