### ISSUE TITLE
Travis PR Builder

### ISSUE THREAD

**Issue by johnament** [arquillian/arquillian-container-weld#27]
I think it would be a good idea if we had a Travis PR builder for this repo.  This way incoming PRs can be tested and confirmed working/not working.

@tremes @bartoszmajsak what do you think?

**Comment by tremes** [comment]
I think `mvn clean install` doesn't test many things in this case so what do you suggest to test it?

**Comment by johnament** [comment]
Then we need to bump up the tests :-)

**Comment by tremes** [comment]
Travis tells me that I don't have admin access to this repository so I am affraid I can't setup PR builder. @bartoszmajsak can you please take a look at this?

**Comment by bartoszmajsak** [comment]
@tremes you should be good to go :) Thanks for taking care of it.

**Comment by tremes** [comment]
Ok so I setup the Travis PR builder at https://travis-ci.org/arquillian/arquillian-container-weld. Thanks
