### ISSUE TITLE
ServiceLoader not loading from all JARs.

### ISSUE THREAD

**Issue by johnament** [arquillian/arquillian-container-weld#39]
@bartoszmajsak  I'm not sure if we're still using github issues or JIRA, feel free to redirect!

##### Issue Overview

The classloader around service loaders doesn't pick up all classes when using TCCL.

##### Expected Behaviour

Given I have a ShrinkWrap archive that creates a WAR, and two JAR files (jarA and jarB), when inside jarB I use `ServiceLoader.load(SomeClass, TCCL)` I get back all services defined in the WAR, jarA and jarB.

##### Current Behaviour

The contents of jarA are ignored.

##### Steps To Reproduce
If you check out https://svn.apache.org/repos/asf/geronimo/components/config/trunk/ and run `mvn clean install -PWeld3` you'll see that several tests fail due to missing config properties.
The config properties are not loaded as the service loader isn't finding the relevant services.  Debug `DefaultConfigBuilder.build` to see the service loader's behavior.

**Comment by tremes** [comment]
Hi @johnament. It's ok to file an issue here I think. I'll check it next week because I am on PTO for the rest of this week.

**Comment by johnament** [comment]
I was able to come up with a simple repro in the weld embedded test suite.  

```
@RunWith(Arquillian.class)
public class ExtensionInJARTestCase {

    @Deployment
    public static Archive<?> createdeployment() {
        JavaArchive jar = ShrinkWrap.create(JavaArchive.class)
                .addAsServiceProvider(Extension.class, WasCalledExtension.class)
                .addClasses(WasCalledExtension.class)
                .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml");
        return ShrinkWrap.create(WebArchive.class)
                .addAsLibraries(jar)
                .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
    }

    @Test
    public void shouldBeAbleToInjectBeanAsInstanceVariable() throws Exception {
        Assert.assertTrue("Extension should have been loaded", WasCalledExtension.wasCalled);
    }
}
```
